version: '3.1'

services:

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 30914182

  redis:
    image: redis
    ports:
      - 6379:6379

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

volumes:
  db-data:
